---
language: en-GB
showStats: true
title: Mini-Me Homepage
layout:
  System Monitoring:
    style: row
    columns: 1  # Full-width section for the top Glances widget
  Glances Grid:
    style: row
    columns: 3  # 3x2 grid for the other Glances widgets
  Developer:
  Entertainment:
