---
# enable or disable the application
homepage_enabled: false
homepage_available_externally: false

# directories
homepage_data_directory: "{{ docker_home }}/homepage"

# network
homepage_hostname: "homepage"
homepage_port: "11111"

# docker
homepage_container_name: "homepage"
homepage_image_name: "ghcr.io/gethomepage/homepage"
homepage_image_tag: "latest"

# specs
homepage_memory: "1g"

# settings
homepage_title: MINI-ME Homepage
homepage_locale: en-GB

# Homepage config files - the variables below are formatted to Homepage YAML config files
homepage_settings_yaml:
  title: "{{ homepage_title }}"
  language: "{{ homepage_locale }}"
  showStats: true
  layout:
    Glances Grid:
      style: row
      columns: 3  # 3x2 grid for the other Glances widgets
  Developer:
  Entertainment:
homepage_services_yaml:
  - Glances Grid:
      - Glances:
          href: http://mini-me:61208
          icon: glances.png
          description: Glances Stats
          widget:
              type: glances
              url: http://mini-me:61208
              version: 4 # required only if running glances v4 or higher, defaults to 3
              metric: info
              diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
              refreshInterval: 2000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
              pointsLimit: 15 # optional, defaults to 15
      - CPU Usage:
          href: http://mini-me:61208
          widget:
              type: glances
              url: http://mini-me:61208
              metric: cpu
              version: 4
              refreshInterval: 2000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
              pointsLimit: 15 # optional, defaults to 15
      - Memory Usage:
          href: http://mini-me:61208
          widget:
              type: glances
              url: http://mini-me:61208
              metric: memory
              version: 4
              refreshInterval: 2000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
              pointsLimit: 15 # optional, defaults to 15
      - Top Processes:
          href: http://mini-me:61208
          widget:
              type: glances
              url: http://mini-me:61208
              metric: process
              version: 4
              refreshInterval: 2000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
              pointsLimit: 15 # optional, defaults to 15
      - Network Usage:
          href: http://mini-me:61208
          widget:
              type: glances
              url: http://mini-me:61208
              metric: network:eth0
              version: 4
              refreshInterval: 2000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
              pointsLimit: 15 # optional, defaults to 15
      - Disk Usage:
          href: http://mini-me:61208
          widget:
              type: glances
              url: http://mini-me:61208
              metric: disk:sda
              version: 4
              diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
              refreshInterval: 2000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
              pointsLimit: 15 # optional, defaults to 15
  - System Tools:
      - Router:
          icon: asus-router
          href: http://192.168.1.1/
          description: Asus Router

homepage_widgets_yaml:
  - search:
      provider: google # google, duckduckgo, bing, baidu, brave or custom
      focus: true # Optional, will set focus to the search bar on page load
      target: _blank # One of _self, _blank, _parent or _top
  - greeting:
      text_size: xl
      text: MINI-ME
  - resources:
      cpu: true
      memory: true
      cputemp: true
      uptime: true
      units: metric # only used by cpu temp
      refresh: 60000 # optional, in ms

homepage_bookmarks_yaml:
  - Developer:
      - MyGithub:
          - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/github-light.svg
            href: https://github.com/crharmon/ansible-nas
      - Ansible-NAS:
          - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/ansible-light.svg
            href: https://ansible-nas.io/
      - Homepage:
          - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/homepage.png
            href: https://gethomepage.dev/

  - Entertainment:
      - YouTube:
          - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/youtube.svg
            href: https://youtube.com/
      - Crunchyroll:
          - icon: si-crunchyroll
            href: https://www.crunchyroll.com/videos/new
      - YouTubeMusic:
          - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/apple-music.svg
            href: https://music.youtube.com/
